"""schema_update

Revision ID: 3489ae0ceaae
Revises: bbc036eb3f04
Create Date: 2026-05-14 16:38:15.037102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3489ae0ceaae"
down_revision: Union[str, None] = "bbc036eb3f04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("author", sa.String(length=256), nullable=False),
        sa.Column("isbn", sa.String(length=13), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("goodreads_id", sa.String(length=64), nullable=True),
        sa.Column("amazon_id", sa.String(length=64), nullable=True),
        sa.Column("cover_image_url", sa.String(length=1024), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("genres", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_amazon_id"), "books", ["amazon_id"], unique=False)
    op.create_index(op.f("ix_books_author"), "books", ["author"], unique=False)
    op.create_index(op.f("ix_books_created_at"), "books", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_books_goodreads_id"), "books", ["goodreads_id"], unique=False
    )
    op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=True)
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.create_index(op.f("ix_books_updated_at"), "books", ["updated_at"], unique=False)
    op.create_table(
        "reading_history",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("read_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_history_book_id"), "reading_history", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_reading_history_created_at"),
        "reading_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_history_id"), "reading_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_reading_history_updated_at"),
        "reading_history",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_history_user_id"), "reading_history", ["user_id"], unique=False
    )
    op.create_table(
        "search_history",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_history_created_at"),
        "search_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_search_history_id"), "search_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_search_history_updated_at"),
        "search_history",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "topic_recommendations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=256), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topic_recommendations_created_at"),
        "topic_recommendations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_recommendations_id"),
        "topic_recommendations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_recommendations_topic"),
        "topic_recommendations",
        ["topic"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_recommendations_updated_at"),
        "topic_recommendations",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_recommendations_user_id"),
        "topic_recommendations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_interests",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=256), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_interests_created_at"),
        "user_interests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_interests_id"), "user_interests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_interests_topic"), "user_interests", ["topic"], unique=False
    )
    op.create_index(
        op.f("ix_user_interests_updated_at"),
        "user_interests",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_interests_user_id"), "user_interests", ["user_id"], unique=False
    )
    op.create_table(
        "book_recommendations",
        sa.Column("search_history_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("recommendation_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["search_history_id"], ["search_history.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_book_recommendations_book_id"),
        "book_recommendations",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_recommendations_created_at"),
        "book_recommendations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_recommendations_id"), "book_recommendations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_book_recommendations_search_history_id"),
        "book_recommendations",
        ["search_history_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_recommendations_updated_at"),
        "book_recommendations",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_recommendations_user_id"),
        "book_recommendations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_book_recommendations_user_id"), table_name="book_recommendations"
    )
    op.drop_index(
        op.f("ix_book_recommendations_updated_at"), table_name="book_recommendations"
    )
    op.drop_index(
        op.f("ix_book_recommendations_search_history_id"),
        table_name="book_recommendations",
    )
    op.drop_index(op.f("ix_book_recommendations_id"), table_name="book_recommendations")
    op.drop_index(
        op.f("ix_book_recommendations_created_at"), table_name="book_recommendations"
    )
    op.drop_index(
        op.f("ix_book_recommendations_book_id"), table_name="book_recommendations"
    )
    op.drop_table("book_recommendations")
    op.drop_index(op.f("ix_user_interests_user_id"), table_name="user_interests")
    op.drop_index(op.f("ix_user_interests_updated_at"), table_name="user_interests")
    op.drop_index(op.f("ix_user_interests_topic"), table_name="user_interests")
    op.drop_index(op.f("ix_user_interests_id"), table_name="user_interests")
    op.drop_index(op.f("ix_user_interests_created_at"), table_name="user_interests")
    op.drop_table("user_interests")
    op.drop_index(
        op.f("ix_topic_recommendations_user_id"), table_name="topic_recommendations"
    )
    op.drop_index(
        op.f("ix_topic_recommendations_updated_at"), table_name="topic_recommendations"
    )
    op.drop_index(
        op.f("ix_topic_recommendations_topic"), table_name="topic_recommendations"
    )
    op.drop_index(
        op.f("ix_topic_recommendations_id"), table_name="topic_recommendations"
    )
    op.drop_index(
        op.f("ix_topic_recommendations_created_at"), table_name="topic_recommendations"
    )
    op.drop_table("topic_recommendations")
    op.drop_index(op.f("ix_search_history_updated_at"), table_name="search_history")
    op.drop_index(op.f("ix_search_history_id"), table_name="search_history")
    op.drop_index(op.f("ix_search_history_created_at"), table_name="search_history")
    op.drop_table("search_history")
    op.drop_index(op.f("ix_reading_history_user_id"), table_name="reading_history")
    op.drop_index(op.f("ix_reading_history_updated_at"), table_name="reading_history")
    op.drop_index(op.f("ix_reading_history_id"), table_name="reading_history")
    op.drop_index(op.f("ix_reading_history_created_at"), table_name="reading_history")
    op.drop_index(op.f("ix_reading_history_book_id"), table_name="reading_history")
    op.drop_table("reading_history")
    op.drop_index(op.f("ix_books_updated_at"), table_name="books")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.drop_index(op.f("ix_books_id"), table_name="books")
    op.drop_index(op.f("ix_books_goodreads_id"), table_name="books")
    op.drop_index(op.f("ix_books_created_at"), table_name="books")
    op.drop_index(op.f("ix_books_author"), table_name="books")
    op.drop_index(op.f("ix_books_amazon_id"), table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
