FROM public.ecr.aws/lambda/python:3.10
WORKDIR "${LAMBDA_TASK_ROOT}"

COPY app.py . 
COPY ./data/books.csv . 
COPY requirements.txt .
COPY .env.example . 


RUN pip install -r requirements.txt 
RUN install torch --index-url https://download.pytorch.org/whl/cpu 

ENV XDG_CACHE_HOME = /tmp
ENV HF_HOME = /tmp
ENV TRANSFORMERS_CACHE = /tmp

CMD ["app.lambda_handler"]