version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment: 
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER = ZENO
      - POSTGRES_PASSWORD = ZENO
      - POSTGRES_POSTGRES_DB = ZENO
    
    healtcheck:
      test: ["CMD-SHELL", "pg_isready -U ZENO"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: public.ecr.aws/ #add ecr image for backend here
    restart: on-failure

    ports: 
      - 8000:8000
    volumes:
      - ./books:/books/artifacts
    
    environment: 
      - DATABASE_STRING=postgresql+pyscopg://ZENO:ZENO@postgres:5432/ZENO
      - PINECONE_API_KEY = <PINECONE_API_KEY>

    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: []
      interval: 5s
      timeout: 5s
      retries: 5
  
  frontend:
  