#Multi-stage build
FROM python:3.13-slim AS builder

LABEL org.opencontainers.image.source=https://github.com/zeno
LABEL org.opencontainers.image.description="Zeno Worker"
LABEL org.opencontainers.image.licenses=Apache-2.0

WORKDIR /usr/app/server

COPY pyproject.toml uv.lock /usr/app/server/

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv && \
    uv sync

COPY /zeno /usr/app/server/zeno


FROM builder

WORKDIR /usr/app/server

COPY --from=builder /usr/app/server/zeno/ /usr/app/server/zeno/
COPY --from=builder /usr/app/server/.venv /usr/app/server/.venv
COPY --from=builder /usr/app/server/pyproject.toml /usr/app/server/pyproject.toml
COPY --from=builder /usr/app/server/uv.lock /usr/app/server/uv.lock

ENV PATH="/usr/app/server/.venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

CMD ["python", "-m", "zeno.worker"]
